run treefmt

diff --git a/pkgs/bin/elixiremanager b/pkgs/bin/elixiremanager
--- a/pkgs/bin/elixiremanager
+++ b/pkgs/bin/elixiremanager
@@ -40,18 +40,18 @@ function version() {
 
 function check_deps() {
     for i in date jq notify-send curl cwebp; do
-        (which $i &>/dev/null) && echo "OK: found $i" || echo "ERROR: $i not found"
+        (which $i &> /dev/null) && echo "OK: found $i" || echo "ERROR: $i not found"
     done
 
     if [[ $wayland == "true" ]]; then
         for i in spectacle; do
-            (which $i &>/dev/null) && echo "OK: found $i" || echo "ERROR: $i not found"
+            (which $i &> /dev/null) && echo "OK: found $i" || echo "ERROR: $i not found"
         done
-        (which wl-copy &>/dev/null) && echo "OK: found wl-clipboard" || echo "ERROR: wl-clipboard not found"
+        (which wl-copy &> /dev/null) && echo "OK: found wl-clipboard" || echo "ERROR: wl-clipboard not found"
     else
-        (which maim &>/dev/null) && echo "OK: maim found" || echo "ERROR: maim not found"
-        (which slop &>/dev/null) && echo "OK: slop found" || echo "ERROR: slop not found"
-        (which xclip &>/dev/null) && echo "OK: found xclip" || echo "ERROR: xclip not found"
+        (which maim &> /dev/null) && echo "OK: maim found" || echo "ERROR: maim not found"
+        (which slop &> /dev/null) && echo "OK: slop found" || echo "ERROR: slop not found"
+        (which xclip &> /dev/null) && echo "OK: found xclip" || echo "ERROR: xclip not found"
     fi
 }
 
@@ -66,7 +66,7 @@ function take_screenshot() {
 function upload_file_and_notify() {
     response=$(curl --compressed --connect-timeout ${upload_connect_timeout} -m ${upload_timeout} --retry ${upload_retries} -H "Authorization: ${apikey}" -F upload=@"${1}" ${apiurl}/upload${is_admin} | jq .url -r | tr -d '\n')
 
-    if [[ ! -z "${response}" ]]; then
+    if [[ -n ${response} ]]; then
         notify-send -t 5000 "Success!" "${response}" -i "${1}" --hint=int:transient:1
         if [[ $wayland == "true" ]]; then
             echo -en "${response}" | wl-copy -f
@@ -82,38 +82,49 @@ while [[ $# != 0 ]]; do
     case "${1}" in
         --help | -h)
             usage ${0}
-            exit 0 ;;
+            exit 0
+            ;;
         --version | -v)
             version ${0}
-            exit 0 ;;
+            exit 0
+            ;;
         --check)
             check_deps
-            exit 0 ;;
+            exit 0
+            ;;
         --area | -a)
             mode=area
-            shift ;;
+            shift
+            ;;
         --full | -f)
             mode=full
-            shift ;;
+            shift
+            ;;
         --keep | -k)
             keep=true
-            shift ;;
+            shift
+            ;;
         --wayland | -w)
             wayland=true
-            shift ;;
+            shift
+            ;;
         --xorg | -x)
             wayland=false
-            shift ;;
+            shift
+            ;;
         --admin)
             is_admin="?admin=true"
-            shift ;;
+            shift
+            ;;
         --noadmin)
             is_admin=""
-            shift ;;
+            shift
+            ;;
         *)
             file_provided=true
             file="${1}"
-            shift ;;
+            shift
+            ;;
     esac
 done
 
@@ -124,7 +135,7 @@ fi
 if [[ -z $file_provided ]]; then
     take_screenshot $mode "${file}"
     size="$(stat -c%s "${file}")"
-    if (( "${size}" > 1024 * 1024 )); then
+    if (("${size}" > 1024 * 1024)); then
         orig_file="${file}"
         file="${webp_filename_format}"
         type="image/webp"
@@ -136,7 +147,7 @@ upload_file_and_notify "${file}${type:+;type=${type}}"
 
 if [[ -z $file_provided && -z $keep ]]; then
     rm -f "${file}"
-    if [[ ! -z $orig_file ]]; then
+    if [[ -n $orig_file ]]; then
         rm -f "${orig_file}"
     fi
 fi
diff --git a/pkgs/bin/make_fcp_x3g b/pkgs/bin/make_fcp_x3g
--- a/pkgs/bin/make_fcp_x3g
+++ b/pkgs/bin/make_fcp_x3g
@@ -91,138 +91,134 @@ DEBUG=0
 
 ############ No user serviceable parts below ############
 
-function usage
-{
-	local prog=$(basename "$0")
-	echo "${prog} [-wPpk] input.gcode   or:   ${prog} -c"
-	echo "Processes G-code file for the FFCP with GPX, after optionally applying certain fixes."
-	echo "Output will be written to a file with the same name and .x3g extension."
-	echo "Options:"
-	echo "  -c: performs a sanity check on all configured paths and warns if they do not"
-	echo "      point to executable files. (Nothing will be processed even if other"
-	echo "      arguments are passed.)"
-	echo "  -w: converts Windows file path to a Linux path inside a WSL environment."
-	echo "  -P: disables all postprocessing and only runs GPX without -p option."
-	echo "  -p: enable -p option of GPX even if -P is used."
-	echo "  -k: keep copy of original file."
+function usage {
+    local prog=$(basename "$0")
+    echo "${prog} [-wPpk] input.gcode   or:   ${prog} -c"
+    echo "Processes G-code file for the FFCP with GPX, after optionally applying certain fixes."
+    echo "Output will be written to a file with the same name and .x3g extension."
+    echo "Options:"
+    echo "  -c: performs a sanity check on all configured paths and warns if they do not"
+    echo "      point to executable files. (Nothing will be processed even if other"
+    echo "      arguments are passed.)"
+    echo "  -w: converts Windows file path to a Linux path inside a WSL environment."
+    echo "  -P: disables all postprocessing and only runs GPX without -p option."
+    echo "  -p: enable -p option of GPX even if -P is used."
+    echo "  -k: keep copy of original file."
 }
 
-
 while getopts ':hcwPpk' opt; do
-	case $opt in
-		h)
-			usage
-			exit
-			;;
-		c)
-			sanity=1
-			;;
-		w)
-			wsl=1
-			;;
-		P)
-			no_postproc=1
-			;;
-		p)
-			force_progress=1
-			;;
-		k)
-			KEEP_ORIG=1
-			;;
-		\?)
-			echo "Ignoring unknown option: -${OPTARG}" >&2
-			;;
-	esac
+    case $opt in
+        h)
+            usage
+            exit
+            ;;
+        c)
+            sanity=1
+            ;;
+        w)
+            wsl=1
+            ;;
+        P)
+            no_postproc=1
+            ;;
+        p)
+            force_progress=1
+            ;;
+        k)
+            KEEP_ORIG=1
+            ;;
+        \?)
+            echo "Ignoring unknown option: -${OPTARG}" >&2
+            ;;
+    esac
 done
 
 if [ -n "${EXTRA_PATH}" ]; then
-	export PATH=$(echo "${PATH}" | perl -pe "s;(:|^)/usr/bin:;\1${EXTRA_PATH}:/usr/bin:;")
+    export PATH=$(echo "${PATH}" | perl -pe "s;(:|^)/usr/bin:;\1${EXTRA_PATH}:/usr/bin:;")
 fi
 
-function sanity_check
-{
-	local fail try_path
+function sanity_check {
+    local fail try_path
 
-	if [ ! -x "${GPX}" ]; then
-		echo "Check failed: the 'GPX' path does not point to an executable file: '${GPX}'"
-		fail=1
-	elif ! "${GPX}" -? > /dev/null; then
-		echo "Check failed: got unexpected result code when running GPX with -? argument."
-		fail=1
-	fi
-	if [ -n "${DUALSTRUDE_SCRIPT}" -a ! -x "${DUALSTRUDE_SCRIPT}" ]; then
-		echo "Check failed: a 'DUALSTRUDE_SCRIPT' path was specified but does not point to an executable file: ${DUALSTRUDE_SCRIPT}"
-		fail=1
-	fi
-	if [ -n "${PWM_SCRIPT}" ]; then
-		if [ ! -x "${PWM_SCRIPT}" ]; then
-			echo "Check failed: a 'PWM_SCRIPT' path was specified but does not point to an executable file: ${PWM_SCRIPT}"
-			fail=1
-		else
-			if ! "${PWM_SCRIPT}" -h > /dev/null; then
-				echo "Check failed: got unexpected result code when running PWM_SCRIPT with -h argument."
-				fail=1
-			fi
-		fi
-	fi
-	if [ -n "${RETRACT_SCRIPT}" ]; then
-		if [ ! -x "${RETRACT_SCRIPT}" ]; then
-			echo "Check failed: a 'RETRACT_SCRIPT' path was specified but does not point to an executable file: ${RETRACT_SCRIPT}"
-			fail=1
-		else
-			if ! "${RETRACT_SCRIPT}" -h > /dev/null; then
-				echo "Check failed: got unexpected result code when running RETRACT_SCRIPT with -h argument."
-				fail=1
-			fi
-		fi
-	fi
-	if grep -qE '(Microsoft|WSL)' /proc/version &> /dev/null; then
-		try_path=$(wslpath -a 'C:\\Test\\file.zip')
-		if [ $? != 0 -o -z "${try_path}" ]; then
-			echo "Check failed: you seem to be inside a WSL environment but the 'wslpath' command is not available or is broken."
-			echo "Make sure you have at least Windows 10 version 1803, and 'wslpath' can be run from a bash shell."
-			fail=1
-		fi
-	fi
+    if [ ! -x "${GPX}" ]; then
+        echo "Check failed: the 'GPX' path does not point to an executable file: '${GPX}'"
+        fail=1
+    elif ! "${GPX}" -? > /dev/null; then
+        echo "Check failed: got unexpected result code when running GPX with -? argument."
+        fail=1
+    fi
+    if [ -n "${DUALSTRUDE_SCRIPT}" -a ! -x "${DUALSTRUDE_SCRIPT}" ]; then
+        echo "Check failed: a 'DUALSTRUDE_SCRIPT' path was specified but does not point to an executable file: ${DUALSTRUDE_SCRIPT}"
+        fail=1
+    fi
+    if [ -n "${PWM_SCRIPT}" ]; then
+        if [ ! -x "${PWM_SCRIPT}" ]; then
+            echo "Check failed: a 'PWM_SCRIPT' path was specified but does not point to an executable file: ${PWM_SCRIPT}"
+            fail=1
+        else
+            if ! "${PWM_SCRIPT}" -h > /dev/null; then
+                echo "Check failed: got unexpected result code when running PWM_SCRIPT with -h argument."
+                fail=1
+            fi
+        fi
+    fi
+    if [ -n "${RETRACT_SCRIPT}" ]; then
+        if [ ! -x "${RETRACT_SCRIPT}" ]; then
+            echo "Check failed: a 'RETRACT_SCRIPT' path was specified but does not point to an executable file: ${RETRACT_SCRIPT}"
+            fail=1
+        else
+            if ! "${RETRACT_SCRIPT}" -h > /dev/null; then
+                echo "Check failed: got unexpected result code when running RETRACT_SCRIPT with -h argument."
+                fail=1
+            fi
+        fi
+    fi
+    if grep -qE '(Microsoft|WSL)' /proc/version &> /dev/null; then
+        try_path=$(wslpath -a 'C:\\Test\\file.zip')
+        if [ $? != 0 -o -z "${try_path}" ]; then
+            echo "Check failed: you seem to be inside a WSL environment but the 'wslpath' command is not available or is broken."
+            echo "Make sure you have at least Windows 10 version 1803, and 'wslpath' can be run from a bash shell."
+            fail=1
+        fi
+    fi
 
-	if [ -z "${fail}" ]; then
-		echo 'All checks seem OK!'
-	fi
+    if [ -z "${fail}" ]; then
+        echo 'All checks seem OK!'
+    fi
 }
 
-
 if [ -n "${sanity}" ]; then
-	sanity_check
-	exit
+    sanity_check
+    exit
 fi
 
-shift $((OPTIND-1))
+shift $((OPTIND - 1))
 inputfile="$1"
 if [ -z "${inputfile}" ]; then
-	echo "Error: argument should be the path to a .gcode file" >&2
-	usage
-	exit 2
+    echo "Error: argument should be the path to a .gcode file" >&2
+    usage
+    exit 2
 fi
 
 if [ -n "${wsl}" ]; then
-	# Although the conversion between Windows and Linux paths seems trivial, it
-	# has many quirks so it is better to rely on the dedicated wslpath tool.
-	inputfile=$(wslpath -a "${inputfile}")
-	if [ $? != 0 -o -z "${inputfile}" ]; then
-		echo "Error: 'wslpath' command not found or failed" >&2
-		exit 3
-	fi
-	echo "Converted Windows path to: '${inputfile}'"
+    # Although the conversion between Windows and Linux paths seems trivial, it
+    # has many quirks so it is better to rely on the dedicated wslpath tool.
+    inputfile=$(wslpath -a "${inputfile}")
+    if [ $? != 0 -o -z "${inputfile}" ]; then
+        echo "Error: 'wslpath' command not found or failed" >&2
+        exit 3
+    fi
+    echo "Converted Windows path to: '${inputfile}'"
 fi
 
 if [ "${DEBUG}" == '1' ]; then
-	output=$(dirname "${inputfile}")
-	sanity_check > "${output}/make_fcp_x3g.check"
+    output=$(dirname "${inputfile}")
+    sanity_check > "${output}/make_fcp_x3g.check"
 fi
 
 if [ ! -r "${inputfile}" ]; then
-	echo "ERROR: input file not found or not readable: ${inputfile}"
-	exit 1
+    echo "ERROR: input file not found or not readable: ${inputfile}"
+    exit 1
 fi
 
 arg_p=''
@@ -232,112 +228,109 @@ stripped=$(echo "${inputfile}" | perl -pe 's/\.gcode$//i')
 warn_file="${stripped}.WARN.txt"
 fail_file="${stripped}.FAIL.txt"
 
-function run_script
-{
-	# Runs a script that prints processed G-code on standard output. If the script exits with an
-	# error code, stderr will be written to $fail_file, otherwise anything appearing on stderr is
-	# written to $warn_file. The original gcode file is overwritten.
-	local name=$1
-	local script=$2
-	local gcode=$3
-	local extra_args=$4
+function run_script {
+    # Runs a script that prints processed G-code on standard output. If the script exits with an
+    # error code, stderr will be written to $fail_file, otherwise anything appearing on stderr is
+    # written to $warn_file. The original gcode file is overwritten.
+    local name=$1
+    local script=$2
+    local gcode=$3
+    local extra_args=$4
 
-	local tempfile warnings
+    local tempfile warnings
 
-	echo "Running ${name} script..."
-	tempfile=$(mktemp)
-	# capture stdout to a file and stderr to a variable
-	warnings=$("${script}" $extra_args "${gcode}" 2>&1 >"${tempfile}")
-	if [ $? != 0 ] ; then
-		if [ -z "${warnings}" ]; then
-			warnings="The ${name} script failed, but without any output on stderr."
-		fi
-		echo "${warnings}" >> "${fail_file}"
-		echo "${warnings}" >&2
-		rm -f "${tempfile}"
-		exit 1
-	fi
-	[ -n "${warnings}" ] && echo "${warnings}" >> "${warn_file}"
-	mv "${tempfile}" "${gcode}"
-	chmod 644 "${gcode}"
+    echo "Running ${name} script..."
+    tempfile=$(mktemp)
+    # capture stdout to a file and stderr to a variable
+    warnings=$("${script}" $extra_args "${gcode}" 2>&1 > "${tempfile}")
+    if [ $? != 0 ]; then
+        if [ -z "${warnings}" ]; then
+            warnings="The ${name} script failed, but without any output on stderr."
+        fi
+        echo "${warnings}" >> "${fail_file}"
+        echo "${warnings}" >&2
+        rm -f "${tempfile}"
+        exit 1
+    fi
+    [ -n "${warnings}" ] && echo "${warnings}" >> "${warn_file}"
+    mv "${tempfile}" "${gcode}"
+    chmod 644 "${gcode}"
 }
 
-function get_highest_z
-{
-	# Extract highest Z value in a G1 command from the last 2048 lines of a file.
-	local gcode=$1
+function get_highest_z {
+    # Extract highest Z value in a G1 command from the last 2048 lines of a file.
+    local gcode=$1
 
-	tail -n 2048 "${gcode}" | grep -oE '^G1 [^;]*Z[0-9]*\.?[0-9]+' | \
-	    awk '{print $2}' | cut -b 2- | sort -g | tail -n 1
+    tail -n 2048 "${gcode}" | grep -oE '^G1 [^;]*Z[0-9]*\.?[0-9]+' |
+        awk '{print $2}' | cut -b 2- | sort -g | tail -n 1
 }
-
 
 if [ -z "${no_postproc}" ]; then
-	rm -f "${warn_file}" "${fail_file}"
+    rm -f "${warn_file}" "${fail_file}"
 
-	if [ "${KEEP_ORIG}" == "1" ]; then
-		cp -p "${inputfile}" "${origfile}"
-	fi
+    if [ "${KEEP_ORIG}" == "1" ]; then
+        cp -p "${inputfile}" "${origfile}"
+    fi
 
-	highest_z=$(get_highest_z "${inputfile}")
-	if [ -z "${highest_z}" ]; then
-		echo 'WARNING: could not find highest Z coordinate. If this is a valid G-code file, the make_fcp_x3g script needs updating.' >> "${warn_file}"
-	else
-		if (( $(echo "${highest_z} > ${Z_MAX}" | bc -l) )); then
-			echo "WARNING: Z coordinates in this file exceed the maximum: ${highest_z} > ${Z_MAX}. This print will likely end in disaster." >> "${warn_file}"
-		fi
-		# Find the current final G1 command, its Z value, and transform it if we need to go higher.
-		final_move=$(grep "^G1 .*${FINAL_Z_MOVE}" "${inputfile}")
-		final_z=$(perl -pe 's/^G1 [^;]*Z(\d*\.?\d+).*$/$1/i' <<< "${final_move}")
-		if (( $(echo "${highest_z} > ${final_z}" | bc -l) )); then
-			# I know this looks horrible but all it does is replacing the Z coordinate with the new one.
-			perl -pi.trashme -e 's/^(G1 [^;]*)Z\d*\.?\d+(.*\Q'"${FINAL_Z_MOVE}"'\E.*)$/$1Z'"${highest_z}"'$2 ; EXTENDED!/i' "${inputfile}"
-			rm -f "${inputfile}.trashme"
-		fi
-	fi
+    highest_z=$(get_highest_z "${inputfile}")
+    if [ -z "${highest_z}" ]; then
+        echo 'WARNING: could not find highest Z coordinate. If this is a valid G-code file, the make_fcp_x3g script needs updating.' >> "${warn_file}"
+    else
+        if (($(echo "${highest_z} > ${Z_MAX}" | bc -l))); then
+            echo "WARNING: Z coordinates in this file exceed the maximum: ${highest_z} > ${Z_MAX}. This print will likely end in disaster." >> "${warn_file}"
+        fi
+        # Find the current final G1 command, its Z value, and transform it if we need to go higher.
+        final_move=$(grep "^G1 .*${FINAL_Z_MOVE}" "${inputfile}")
+        final_z=$(perl -pe 's/^G1 [^;]*Z(\d*\.?\d+).*$/$1/i' <<< "${final_move}")
+        if (($(echo "${highest_z} > ${final_z}" | bc -l))); then
+            # I know this looks horrible but all it does is replacing the Z coordinate with the new one.
+            perl -pi.trashme -e 's/^(G1 [^;]*)Z\d*\.?\d+(.*\Q'"${FINAL_Z_MOVE}"'\E.*)$/$1Z'"${highest_z}"'$2 ; EXTENDED!/i' "${inputfile}"
+            rm -f "${inputfile}.trashme"
+        fi
+    fi
 
-	if [ -x "${DUALSTRUDE_SCRIPT}" ] && grep -q 'FOR USE IN COMBINATION WITH DUALSTRUSION POST-PROCESSING SCRIPT .*ONLY' "${inputfile}" 2>/dev/null; then
-		run_script 'dualstrusion' "${DUALSTRUDE_SCRIPT}" "${inputfile}"
-	elif grep -qE ';- - - Custom G-code for (left|right) extruder printing' "${inputfile}" 2>/dev/null; then
-		# Work around bug in Slic3r that always causes T0 to be heated if the second layer has a
-		# different filament temperature. See https://github.com/alexrj/Slic3r/issues/4003
-		# This hack simply wipes the T argument, which works by the grace of how GPX processes the commands.
-		if grep -qE '^M104 S.+ T.+; set temperature$' "${inputfile}"; then
-			# I am entirely relying here on the assumption that any version of Slic3r will
-			# keep on printing the code with a comment exactly like this.
-			echo "Fixing incorrect M104 command for single-extrusion setup"
-			perl -pi.trashme -e 's/^M104 S(\S+) (T.*); set temperature$/M104 S$1 ; POSTPROCESS FIX: $2 ARGUMENT REMOVED/' "${inputfile}"
-			rm -f "${inputfile}.trashme"
-		fi
-	fi
+    if [ -x "${DUALSTRUDE_SCRIPT}" ] && grep -q 'FOR USE IN COMBINATION WITH DUALSTRUSION POST-PROCESSING SCRIPT .*ONLY' "${inputfile}" 2> /dev/null; then
+        run_script 'dualstrusion' "${DUALSTRUDE_SCRIPT}" "${inputfile}"
+    elif grep -qE ';- - - Custom G-code for (left|right) extruder printing' "${inputfile}" 2> /dev/null; then
+        # Work around bug in Slic3r that always causes T0 to be heated if the second layer has a
+        # different filament temperature. See https://github.com/alexrj/Slic3r/issues/4003
+        # This hack simply wipes the T argument, which works by the grace of how GPX processes the commands.
+        if grep -qE '^M104 S.+ T.+; set temperature$' "${inputfile}"; then
+            # I am entirely relying here on the assumption that any version of Slic3r will
+            # keep on printing the code with a comment exactly like this.
+            echo "Fixing incorrect M104 command for single-extrusion setup"
+            perl -pi.trashme -e 's/^M104 S(\S+) (T.*); set temperature$/M104 S$1 ; POSTPROCESS FIX: $2 ARGUMENT REMOVED/' "${inputfile}"
+            rm -f "${inputfile}.trashme"
+        fi
+    fi
 
-	if grep -qE '^M83(;| |$)' "${inputfile}"; then
-		# Workaround for issue #60 in gCodeViewer (gcode.ws) that messes up rendering if an M83 is followed by a G90.
-		# Again, I'm assuming Slic3r will always print the line exactly like this:
-		perl -pi.trashme -e 's/^(G90 ; use absolute coordinates)$/$1\nM83; POSTPROCESS workaround for relative E in gcode.ws/' "${inputfile}"
-		rm -f "${inputfile}.trashme"
-	fi
+    if grep -qE '^M83(;| |$)' "${inputfile}"; then
+        # Workaround for issue #60 in gCodeViewer (gcode.ws) that messes up rendering if an M83 is followed by a G90.
+        # Again, I'm assuming Slic3r will always print the line exactly like this:
+        perl -pi.trashme -e 's/^(G90 ; use absolute coordinates)$/$1\nM83; POSTPROCESS workaround for relative E in gcode.ws/' "${inputfile}"
+        rm -f "${inputfile}.trashme"
+    fi
 
-	if [ -x "${RETRACT_SCRIPT}" ]; then
-		run_script 'retraction' "${RETRACT_SCRIPT}" "${inputfile}"
-	fi
+    if [ -x "${RETRACT_SCRIPT}" ]; then
+        run_script 'retraction' "${RETRACT_SCRIPT}" "${inputfile}"
+    fi
 
-	if [ -x "${PWM_SCRIPT}" ]; then
-		run_script 'fan PWM post-processing' "${PWM_SCRIPT}" "${inputfile}" $PWM_OPTS
-	fi
+    if [ -x "${PWM_SCRIPT}" ]; then
+        run_script 'fan PWM post-processing' "${PWM_SCRIPT}" "${inputfile}" $PWM_OPTS
+    fi
 
-	# -p overrides % display with something that better approximates total print time than merely
-	# mapping the Z coordinate to a percentage. It still is not perfect but at least gives a sensible
-	# ballpark figure. For this to work properly, the start GCode block must end with "M73 P1 ;@body"
-	# according to typical cargo cult, although a peek in GPX source code reveals that either M73 P1
-	# or @body will work.
-	arg_p=' -p'
+    # -p overrides % display with something that better approximates total print time than merely
+    # mapping the Z coordinate to a percentage. It still is not perfect but at least gives a sensible
+    # ballpark figure. For this to work properly, the start GCode block must end with "M73 P1 ;@body"
+    # according to typical cargo cult, although a peek in GPX source code reveals that either M73 P1
+    # or @body will work.
+    arg_p=' -p'
 fi
 
 if [ -n "${force_progress}" ]; then
-	arg_p=' -p'
+    arg_p=' -p'
 fi
 
 # TODO: errors from this command should also be collected. Perhaps filter out the M132 warnings,
-# although they should not appear with properly written start code. 
+# although they should not appear with properly written start code.
 "${GPX}" $arg_p -m "${MACHINE}" "${inputfile}"
